import hashlib
import hmac
import json
import os
import textwrap
from dataclasses import dataclass
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any, Optional

import httpx

from ..core.config import settings
from ..models import (
    BillingInvoice,
    BillingInvoiceStatus,
    BillingPayment,
    BillingReceipt,
    Client,
    CustomerPortalAccount,
    CustomerPortalNotification,
    OperationRecord,
    PaymentProvider,
    PaymentProviderConfig,
    PaymentStatus,
    PaymentWebhookEvent,
    PortalNotificationSeverity,
)


@dataclass
class ProviderVerificationResult:
    reference: str
    amount: Decimal
    currency: str
    status: str
    raw: dict[str, Any]


@dataclass
class ActivationDispatchResult:
    success: bool
    status: str
    message: str
    external_reference: Optional[str] = None
    response_payload: Optional[dict[str, Any]] = None


def _env_value(env_name: Optional[str], fallback: Optional[str] = None) -> Optional[str]:
    if env_name:
        value = os.getenv(env_name)
        if value:
            return value
    if fallback:
        return os.getenv(fallback)
    return None


def _pdf_safe_text(value: Any) -> str:
    text = str(value or "")
    return text.encode("latin-1", "replace").decode("latin-1").replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _format_money(amount: Decimal | int | float | str) -> str:
    decimal_amount = Decimal(str(amount or 0))
    return f"{decimal_amount:,.2f}"


def _coerce_branding(branding: Optional[dict[str, Any]]) -> dict[str, str]:
    raw = branding or {}
    return {
        "display_name": str(raw.get("display_name") or raw.get("company_name") or "").strip(),
        "support_email": str(raw.get("support_email") or "").strip(),
        "support_phone": str(raw.get("support_phone") or "").strip(),
        "footer_note": str(raw.get("footer_note") or "Generated by VUX Customer Portal").strip(),
    }


def _build_text_pdf(title: str, lines: list[str]) -> bytes:
    wrapped_lines: list[str] = []
    for line in lines:
        for wrapped in textwrap.wrap(line, width=88) or [""]:
            wrapped_lines.append(wrapped)

    y_position = 780
    stream_lines = ["BT", "/F1 22 Tf", "50 800 Td", f"({_pdf_safe_text(title)}) Tj", "ET"]
    for line in wrapped_lines:
        stream_lines.extend(
            [
                "BT",
                "/F1 11 Tf",
                f"50 {y_position} Td",
                f"({_pdf_safe_text(line)}) Tj",
                "ET",
            ]
        )
        y_position -= 16

    stream = "\n".join(stream_lines).encode("latin-1", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>".encode("latin-1"),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        f"<< /Length {len(stream)} >>\nstream\n".encode("latin-1") + stream + b"\nendstream",
    ]

    pdf = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("latin-1"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_position = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("latin-1"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("latin-1"))
    pdf.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_position}\n%%EOF".encode("latin-1")
    )
    return bytes(pdf)


def resolve_activation_service_config() -> dict[str, Any]:
    return {
        "endpoint": os.getenv("SERVICE_ACTIVATION_ENDPOINT"),
        "api_key": os.getenv("SERVICE_ACTIVATION_API_KEY"),
        "timeout_seconds": float(os.getenv("SERVICE_ACTIVATION_TIMEOUT_SECONDS", "15")),
    }


def resolve_provider_credentials(config: PaymentProviderConfig) -> dict[str, Optional[str]]:
    fallback_secret = "PAYSTACK_SECRET_KEY" if config.provider == PaymentProvider.PAYSTACK else "FLUTTERWAVE_SECRET_KEY"
    fallback_public = "PAYSTACK_PUBLIC_KEY" if config.provider == PaymentProvider.PAYSTACK else "FLUTTERWAVE_PUBLIC_KEY"
    fallback_webhook = "PAYSTACK_WEBHOOK_SECRET" if config.provider == PaymentProvider.PAYSTACK else "FLUTTERWAVE_WEBHOOK_SECRET"
    return {
        "public_key": _env_value(config.public_key_env, fallback_public),
        "secret_key": _env_value(config.secret_key_env, fallback_secret),
        "webhook_secret": _env_value(config.webhook_secret_env, fallback_webhook) or _env_value(config.secret_key_env, fallback_secret),
    }


async def initialize_checkout(
    config: PaymentProviderConfig,
    payment: BillingPayment,
    client: Client,
    reference: str,
) -> dict[str, Optional[str]]:
    creds = resolve_provider_credentials(config)
    if not creds["secret_key"] or config.provider == PaymentProvider.MANUAL:
        return {
            "checkout_url": None,
            "access_code": None,
            "provider_reference": reference,
            "provider_message": "Payment request created. Provider credentials are not configured yet.",
        }

    payload = {
        "reference": reference,
        "amount": int(Decimal(payment.amount) * 100),
        "currency": config.currency,
        "email": client.email or f"{client.client_id}@portal.local",
        "metadata": {
            "customer_id": client.client_id,
            "client_id": client.id,
            "tenant_id": getattr(payment, "tenant_id", None),
            "payment_id": payment.payment_id,
        },
    }
    async with httpx.AsyncClient(timeout=20) as http:
        if config.provider == PaymentProvider.PAYSTACK:
            response = await http.post(
                "https://api.paystack.co/transaction/initialize",
                headers={"Authorization": f"Bearer {creds['secret_key']}"},
                json={
                    **payload,
                    "callback_url": config.callback_url,
                },
            )
            response.raise_for_status()
            data = response.json().get("data", {})
            return {
                "checkout_url": data.get("authorization_url"),
                "access_code": data.get("access_code"),
                "provider_reference": data.get("reference", reference),
                "provider_message": "Redirect customer to the Paystack checkout URL.",
            }

        response = await http.post(
            "https://api.flutterwave.com/v3/payments",
            headers={"Authorization": f"Bearer {creds['secret_key']}"},
            json={
                "tx_ref": reference,
                "amount": float(payment.amount),
                "currency": config.currency,
                "redirect_url": config.callback_url,
                "customer": {
                    "email": client.email or f"{client.client_id}@portal.local",
                    "name": client.name,
                    "phonenumber": client.phone,
                },
                "customizations": {
                    "title": "VUX Customer Portal Payment",
                    "description": payment.notes or "Subscription payment",
                },
                "meta": payload["metadata"],
            },
        )
        response.raise_for_status()
        data = response.json().get("data", {})
        return {
            "checkout_url": data.get("link"),
            "access_code": None,
            "provider_reference": reference,
            "provider_message": "Redirect customer to the Flutterwave checkout URL.",
        }


def verify_webhook_signature(provider: PaymentProvider, raw_body: bytes, signature: Optional[str], config: PaymentProviderConfig) -> bool:
    creds = resolve_provider_credentials(config)
    secret = creds["webhook_secret"] or ""
    if not signature or not secret:
        return False
    if provider == PaymentProvider.PAYSTACK:
        expected = hmac.new(secret.encode("utf-8"), raw_body, hashlib.sha512).hexdigest()
        return hmac.compare_digest(expected, signature)
    return hmac.compare_digest(secret, signature)


async def verify_provider_transaction(
    provider: PaymentProvider,
    config: PaymentProviderConfig,
    reference: str,
) -> ProviderVerificationResult:
    creds = resolve_provider_credentials(config)
    if not creds["secret_key"]:
        raise ValueError("Provider secret key is not configured")

    async with httpx.AsyncClient(timeout=20) as http:
        if provider == PaymentProvider.PAYSTACK:
            response = await http.get(
                f"https://api.paystack.co/transaction/verify/{reference}",
                headers={"Authorization": f"Bearer {creds['secret_key']}"},
            )
            response.raise_for_status()
            raw = response.json().get("data", {})
            amount = Decimal(str(raw.get("amount", 0))) / Decimal("100")
            return ProviderVerificationResult(
                reference=raw.get("reference", reference),
                amount=amount,
                currency=raw.get("currency", config.currency),
                status=raw.get("status", "pending"),
                raw=raw,
            )

        response = await http.get(
            f"https://api.flutterwave.com/v3/transactions/verify_by_reference?tx_ref={reference}",
            headers={"Authorization": f"Bearer {creds['secret_key']}"},
        )
        response.raise_for_status()
        raw = response.json().get("data", {})
        return ProviderVerificationResult(
            reference=raw.get("tx_ref", reference),
            amount=Decimal(str(raw.get("amount", 0))),
            currency=raw.get("currency", config.currency),
            status=raw.get("status", "pending"),
            raw=raw,
        )


def render_invoice_html(
    invoice: BillingInvoice,
    client: Client,
    tenant_name: str,
    branding: Optional[dict[str, Any]] = None,
) -> str:
    brand = _coerce_branding(branding)
    header_name = brand["display_name"] or tenant_name
    line_items = invoice.line_items or []
    rows = "".join(
        f"<tr><td>{item.get('description','Item')}</td><td>{item.get('quantity',1)}</td><td>{item.get('amount', invoice.amount)}</td></tr>"
        for item in line_items
    )
    return f"""
    <html>
      <head>
        <title>Invoice {invoice.invoice_number}</title>
        <style>
          body {{ font-family: Arial, sans-serif; padding: 32px; color: #111827; }}
          table {{ width: 100%; border-collapse: collapse; margin-top: 24px; }}
          th, td {{ border-bottom: 1px solid #e5e7eb; padding: 10px; text-align: left; }}
          .meta {{ margin-top: 8px; color: #4b5563; }}
        </style>
      </head>
      <body>
        <h1>{header_name} Invoice</h1>
        <div class="meta">Invoice No: {invoice.invoice_number}</div>
        <div class="meta">Customer: {client.name} ({client.client_id})</div>
        <div class="meta">Issued: {invoice.issued_at}</div>
        <div class="meta">Due: {invoice.due_date}</div>
        <div class="meta">Support: {brand["support_email"] or "Not configured"} {brand["support_phone"] or ""}</div>
        <table>
          <thead>
            <tr><th>Description</th><th>Qty</th><th>Amount</th></tr>
          </thead>
          <tbody>{rows}</tbody>
        </table>
        <h2>Total: {invoice.currency} {invoice.amount}</h2>
        <p class="meta">{brand["footer_note"]}</p>
      </body>
    </html>
    """


def render_receipt_html(
    receipt: BillingReceipt,
    invoice: BillingInvoice,
    client: Client,
    tenant_name: str,
    branding: Optional[dict[str, Any]] = None,
) -> str:
    brand = _coerce_branding(branding)
    header_name = brand["display_name"] or tenant_name
    return f"""
    <html>
      <head>
        <title>Receipt {receipt.receipt_number}</title>
        <style>
          body {{ font-family: Arial, sans-serif; padding: 32px; color: #111827; }}
          .meta {{ margin-top: 8px; color: #4b5563; }}
        </style>
      </head>
      <body>
        <h1>{header_name} Receipt</h1>
        <div class="meta">Receipt No: {receipt.receipt_number}</div>
        <div class="meta">Invoice No: {invoice.invoice_number}</div>
        <div class="meta">Customer: {client.name} ({client.client_id})</div>
        <div class="meta">Payment Reference: {receipt.payment_reference}</div>
        <div class="meta">Payment Method: {receipt.payment_method or 'N/A'}</div>
        <div class="meta">Issued: {receipt.issued_at}</div>
        <div class="meta">Support: {brand["support_email"] or "Not configured"} {brand["support_phone"] or ""}</div>
        <h2>Amount Paid: {receipt.currency} {receipt.amount}</h2>
        <p class="meta">{brand["footer_note"]}</p>
      </body>
    </html>
    """


def render_invoice_pdf(
    invoice: BillingInvoice,
    client: Client,
    tenant_name: str,
    branding: Optional[dict[str, Any]] = None,
) -> bytes:
    brand = _coerce_branding(branding)
    header_name = brand["display_name"] or tenant_name
    item_lines = invoice.line_items or [{"description": invoice.plan_name, "quantity": 1, "amount": invoice.amount}]
    lines = [
        f"Invoice Number: {invoice.invoice_number}",
        f"Customer: {client.name} ({client.client_id})",
        f"Plan: {invoice.plan_name}",
        f"Issued At: {invoice.issued_at}",
        f"Due Date: {invoice.due_date}",
        f"Status: {invoice.status.value if hasattr(invoice.status, 'value') else invoice.status}",
        "",
        "Line Items:",
    ]
    for item in item_lines:
        lines.append(f"- {item.get('description', 'Item')} | Qty {item.get('quantity', 1)} | {invoice.currency} {_format_money(item.get('amount', invoice.amount))}")
    lines.extend(
        [
            "",
            f"Total: {invoice.currency} {_format_money(invoice.amount)}",
            f"Balance: {invoice.currency} {_format_money(invoice.balance)}",
            f"Support: {brand['support_email'] or 'Not configured'} {brand['support_phone'] or ''}".strip(),
            brand["footer_note"],
        ]
    )
    return _build_text_pdf(f"{header_name} Invoice", lines)


def render_receipt_pdf(
    receipt: BillingReceipt,
    invoice: BillingInvoice,
    client: Client,
    tenant_name: str,
    branding: Optional[dict[str, Any]] = None,
) -> bytes:
    brand = _coerce_branding(branding)
    header_name = brand["display_name"] or tenant_name
    lines = [
        f"Receipt Number: {receipt.receipt_number}",
        f"Invoice Number: {invoice.invoice_number}",
        f"Customer: {client.name} ({client.client_id})",
        f"Payment Reference: {receipt.payment_reference}",
        f"Payment Method: {receipt.payment_method or 'N/A'}",
        f"Issued At: {receipt.issued_at}",
        "",
        f"Amount Paid: {receipt.currency} {_format_money(receipt.amount)}",
        f"Original Invoice Amount: {invoice.currency} {_format_money(invoice.amount)}",
        f"Support: {brand['support_email'] or 'Not configured'} {brand['support_phone'] or ''}".strip(),
        brand["footer_note"],
    ]
    return _build_text_pdf(f"{header_name} Receipt", lines)


def build_activation_payload(client: Client, payment: BillingPayment, invoice: BillingInvoice) -> dict[str, Any]:
    return {
        "customer_id": client.client_id,
        "client_id": client.id,
        "payment_id": payment.payment_id,
        "invoice_number": invoice.invoice_number,
        "requested_at": datetime.utcnow().isoformat(),
        "status": "pending_service_activation",
        "integration": "existing_radius_interface_only",
    }


async def dispatch_service_activation(record: OperationRecord) -> ActivationDispatchResult:
    config = resolve_activation_service_config()
    endpoint = config["endpoint"]
    if not endpoint:
        return ActivationDispatchResult(
            success=False,
            status="pending",
            message="Activation service endpoint is not configured.",
        )

    headers = {"Content-Type": "application/json"}
    if config["api_key"]:
        headers["Authorization"] = f"Bearer {config['api_key']}"

    payload = {
        **(record.payload or {}),
        "operation_record_id": record.id,
        "record_key": record.record_key,
        "module": record.module,
    }
    try:
        async with httpx.AsyncClient(timeout=config["timeout_seconds"]) as http:
            response = await http.post(endpoint, headers=headers, json=payload)
            response.raise_for_status()
            data = response.json() if response.content else {}
    except Exception as exc:
        return ActivationDispatchResult(
            success=False,
            status="retry_pending",
            message=str(exc),
        )

    return ActivationDispatchResult(
        success=bool(data.get("accepted", True)),
        status=str(data.get("status") or ("completed" if data.get("completed") else "processing")),
        message=str(data.get("message") or "Activation request submitted successfully."),
        external_reference=data.get("external_reference") or data.get("job_id") or data.get("reference"),
        response_payload=data if isinstance(data, dict) else {"raw": data},
    )
