"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useMemo, useRef } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import type { GeoPoint, NodeType } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";

const infrastructureNodeTypes = ["pop", "olt", "odf", "cabinet", "mst", "pole", "manhole", "closure"] as const;
const nodeTypeGroups = [
  {
    label: "Core Network",
    options: [
      { value: "pop", label: "POP" },
      { value: "olt", label: "OLT" },
      { value: "odf", label: "ODF" },
    ],
  },
  {
    label: "Distribution Network",
    options: [
      { value: "cabinet", label: "Cabinet" },
      { value: "mst", label: "MST" },
      { value: "closure", label: "Closure" },
    ],
  },
  {
    label: "Civil / Outside Plant",
    options: [
      { value: "pole", label: "Pole" },
      { value: "manhole", label: "Manhole / Handhole" },
    ],
  },
] as const;

const nodeTypePrefixes: Record<(typeof infrastructureNodeTypes)[number], string> = {
  pop: "POP",
  olt: "OLT",
  odf: "ODF",
  cabinet: "CAB",
  mst: "MST",
  pole: "POL",
  manhole: "MH",
  closure: "CLS",
};

const schema = z.object({
  name: z.string().min(3, "Name is required"),
  latitude: z.coerce.number().min(-90).max(90),
  longitude: z.coerce.number().min(-180).max(180),
  type: z.enum(infrastructureNodeTypes),
});

type FormValues = z.infer<typeof schema>;

type AreaSuggestion = {
  label: string;
  location: GeoPoint;
};

type AddNodeFormProps = {
  onSubmit: (payload: { name: string; type: Extract<NodeType, (typeof infrastructureNodeTypes)[number]>; location: GeoPoint }) => void;
  areaSuggestions?: AreaSuggestion[];
};

function buildAreaToken(label?: string) {
  if (!label) return "SITE";
  const token = label
    .split(/[,-]/)[0]
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .join("-");
  return token ? token.toUpperCase() : "SITE";
}

function calculatePointDistance(pointA: GeoPoint, pointB: GeoPoint) {
  const latDiff = pointA.lat - pointB.lat;
  const lngDiff = pointA.lng - pointB.lng;
  return Math.sqrt(latDiff * latDiff + lngDiff * lngDiff);
}

export function AddNodeForm({ onSubmit, areaSuggestions = [] }: AddNodeFormProps) {
  const form = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      name: "",
      latitude: 6.455,
      longitude: 3.476,
      type: "mst",
    },
  });
  const previousTypeRef = useRef<FormValues["type"]>("mst");
  const nameValue = form.watch("name");
  const typeValue = form.watch("type");
  const latitudeValue = form.watch("latitude");
  const longitudeValue = form.watch("longitude");
  const nearestAreaLabel = useMemo(() => {
    if (!areaSuggestions.length) return undefined;
    const currentPoint = { lat: latitudeValue, lng: longitudeValue };
    const nearest = areaSuggestions.reduce<{ label: string; distance: number } | null>((closest, area) => {
      const distance = calculatePointDistance(currentPoint, area.location);
      if (!closest || distance < closest.distance) return { label: area.label, distance };
      return closest;
    }, null);
    return nearest?.label;
  }, [areaSuggestions, latitudeValue, longitudeValue]);
  const suggestedAreaToken = useMemo(() => buildAreaToken(nearestAreaLabel), [nearestAreaLabel]);

  useEffect(() => {
    const previousType = previousTypeRef.current;
    const previousPrefix = nodeTypePrefixes[previousType];
    const nextPrefix = nodeTypePrefixes[typeValue];
    const trimmedName = nameValue.trim();
    const looksAutoGenerated =
      trimmedName === "" ||
      /^([A-Z]{2,4})-[A-Z0-9-]+-\d{3}$/.test(trimmedName) ||
      trimmedName.startsWith(`${previousPrefix}-`);

    if (looksAutoGenerated) {
      form.setValue("name", `${nextPrefix}-${suggestedAreaToken}-001`, { shouldDirty: trimmedName.length > 0 });
    }

    previousTypeRef.current = typeValue;
  }, [form, nameValue, suggestedAreaToken, typeValue]);

  const submit = form.handleSubmit((values) => {
    onSubmit({
      name: values.name.trim(),
      type: values.type,
      location: { lat: values.latitude, lng: values.longitude },
    });
    form.reset({
      name: "",
      latitude: values.latitude,
      longitude: values.longitude,
      type: values.type,
    });
  });

  return (
    <form onSubmit={submit} className="space-y-2">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Add Node (Coordinates)</p>
      <p className="text-[11px] text-muted-foreground">
        Add POP, OLT, ODF, cabinet, MST, pole, manhole, or closure infrastructure directly by GPS coordinates.
      </p>

      <div>
        <Label htmlFor="node-name" className="text-xs">
          Name
        </Label>
        <Input id="node-name" placeholder="MST-KUKA-001" {...form.register("name")} />
        <p className="mt-1 text-[11px] text-muted-foreground">
          Suggested format: {nodeTypePrefixes[typeValue]}-{suggestedAreaToken}-001
          {nearestAreaLabel ? ` from nearest area: ${nearestAreaLabel}` : ""}
        </p>
      </div>

      <div className="grid grid-cols-2 gap-2">
        <div>
          <Label htmlFor="node-lat" className="text-xs">
            Latitude
          </Label>
          <Input id="node-lat" type="number" step="any" {...form.register("latitude")} />
        </div>
        <div>
          <Label htmlFor="node-lng" className="text-xs">
            Longitude
          </Label>
          <Input id="node-lng" type="number" step="any" {...form.register("longitude")} />
        </div>
      </div>

      <div>
        <Label htmlFor="node-type" className="text-xs">
          Type
        </Label>
        <Select id="node-type" {...form.register("type")}>
          {nodeTypeGroups.map((group) => (
            <optgroup key={group.label} label={group.label}>
              {group.options.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </optgroup>
          ))}
        </Select>
      </div>

      <Button type="submit" size="sm" className="w-full">
        Create Infrastructure Node
      </Button>
    </form>
  );
}
